## Correlation testing

In [ ]:
import os 
os.getcwd()

In [3]:
os.chdir("C:/Users/User/Desktop/project")

In [4]:
os.getcwd()

'C:\\Users\\User\\Desktop\\project'

In [5]:
import pandas as pd 

df = pd.read_csv("general_data.csv")

In [6]:
df.head()

,Age,Attrition,BusinessTravel,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeID,Gender,...,NumCompaniesWorked,Over18,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
0,51,No,Travel_Rarely,Sales,6,2,Life Sciences,1,1,Female,...,1.0,Y,11,8,0,1.0,6,1,0,0
1,31,Yes,Travel_Frequently,Research & Development,10,1,Life Sciences,1,2,Female,...,0.0,Y,23,8,1,6.0,3,5,1,4
2,32,No,Travel_Frequently,Research & Development,17,4,Other,1,3,Male,...,1.0,Y,15,8,3,5.0,2,5,0,3
3,38,No,Non-Travel,Research & Development,2,5,Life Sciences,1,4,Male,...,3.0,Y,11,8,3,13.0,5,8,7,5
4,32,No,Travel_Rarely,Research & Development,10,1,Medical,1,5,Male,...,4.0,Y,12,8,2,9.0,2,6,0,4

In [8]:
df.Attrition = df.Attrition.map({"Yes" : 1, "No" : 0}) 
df.Gender = df.Gender.map({'Male' : 1, 'Female' : 0})

In [14]:
df1 = df.dropna()

__Correlation Matrix__

In [19]:
df1.corr()

,Age,Attrition,DistanceFromHome,Education,EmployeeCount,EmployeeID,Gender,JobLevel,MonthlyIncome,NumCompaniesWorked,PercentSalaryHike,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,YearsAtCompany,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.158399,0.007376,-0.033900,NaN,0.008105,-0.040625,-0.001137,-0.045163,0.299527,-0.032561,NaN,-0.031504,0.680037,-0.028962,0.311281,0.215650,0.201580
Attrition,-0.158399,1.000000,-0.009449,-0.017106,NaN,-0.004621,0.018396,-0.012382,-0.030160,0.042831,0.033153,NaN,-0.008164,-0.169670,-0.047586,-0.133003,-0.031423,-0.154692
DistanceFromHome,0.007376,-0.009449,1.000000,-0.007491,NaN,-0.000326,-0.042610,-0.039990,-0.022757,-0.014449,0.037720,NaN,0.009353,0.009574,-0.008957,0.030746,0.002243,0.021773
Education,-0.033900,-0.017106,-0.007491,1.000000,NaN,-0.009389,-0.017671,0.045822,0.007289,-0.016210,-0.041054,NaN,0.002386,-0.009228,0.009939,0.005997,0.023457,0.005645
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmployeeID,0.008105,-0.004621,-0.000326,-0.009389,NaN,1.000000,-0.012812,-0.003090,0.007865,0.000719,-0.004877,NaN,-0.013488,-0.001688,-0.012102,0.004117,0.000814,0.009079
Gender,-0.040625,0.018396,-0.042610,-0.017671,NaN,-0.012812,1.000000,-0.026019,0.006805,-0.066860,0.013207,NaN,0.022043,-0.028251,-0.032597,-0.018659,-0.023018,0.002688
JobLevel,-0.001137,-0.012382,-0.039990,0.045822,NaN,-0.003090,-0.026019,1.000000,0.046688,-0.009759,0.010874,NaN,0.000365,-0.036293,-0.031931,-0.063360,-0.059680,-0.053898
MonthlyIncome,-0.045163,-0.030160,-0.022757,0.007289,NaN,0.007865,0.006805,0.046688,1.000000,-0.021446,0.004607,NaN,0.027242,-0.034398,0.049780,0.000088,0.064470,0.023095
NumCompaniesWorked,0.299527,0.042831,-0.014449,-0.016210,NaN,0.000719,-0.066860,-0.009759,-0.021446,1.000000,0.030064,NaN,0.016291,0.238807,-0.031335,-0.117213,-0.035855,-0.109372
PercentSalaryHike,-0.032561,0.033153,0.037720,-0.041054,NaN,-0.004877,0.013207,0.010874,0.004607,0.030064,1.000000,NaN,0.012104,-0.018480,-0.036720,-0.029022,-0.028654,-0.039687
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,-0.031504,-0.008164,0.009353,0.002386,NaN,-0.013488,0.022043,0.000365,0.027242,0.016291,0.012104,NaN,1.000000,0.003138,-0.068028,0.009369,0.019889,0.019398
TotalWorkingYears,0.680037,-0.169670,0.009574,-0.009228,NaN,-0.001688,-0.028251,-0.036293,-0.034398,0.238807,-0.018480,NaN,0.003138,1.000000,-0.041459,0.627738,0.404058,0.458640
TrainingTimesLastYear,-0.028962,-0.047586,-0.008957,0.009939,NaN,-0.012102,-0.032597,-0.031931,0.049780,-0.031335,-0.036720,NaN,-0.068028,-0.041459,1.000000,-0.010447,0.015340,-0.015792
YearsAtCompany,0.311281,-0.133003,0.030746,0.005997,NaN,0.004117,-0.018659,-0.063360,0.000088,-0.117213,-0.029022,NaN,0.009369,0.627738,-0.010447,1.000000,0.618722,0.769161
YearsSinceLastPromotion,0.215650,-0.031423,0.002243,0.023457,NaN,0.000814,-0.023018,-0.059680,0.064470,-0.035855,-0.028654,NaN,0.019889,0.404058,0.015340,0.618722,1.000000,0.510341
YearsWithCurrManager,0.201580,-0.154692,0.021773,0.005645,NaN,0.009079,0.002688,-0.053898,0.023095,-0.109372,-0.039687,NaN,0.019398,0.458640,-0.015792,0.769161,0.510341,1.000000

__Correlation coefficient between Attrition and Age__

In [62]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.Age)

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.15839867954096148
Hence they are negatively correlated

__Correlation coefficient between Attrition and DistanceFromHome__

In [63]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.DistanceFromHome)

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.009448638515156127
Hence they are negatively correlated

__Correlation coefficient between Attrition and Education__

In [64]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.Education) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.01710630705027809
Hence they are negatively correlated

__Correlation coefficient between Attrition and Gender__

In [65]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.Gender) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : 0.018396425194440544
Hence they are positively correlated

__Correlation coefficient between Attrition and JobLevel__

In [66]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.JobLevel) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.012381569720790162
Hence they are negatively correlated

__Correlation coefficient between Attrition and MonthlyIncome__

In [67]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.MonthlyIncome) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.030160293808459582
Hence they are negatively correlated

__Correlation coefficient between Attrition and PercentSalaryHike__

In [68]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.PercentSalaryHike) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : 0.033153037135465274
Hence they are positively correlated

__Correlation coefficient between Attrition and StockOptionLevel__

In [69]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.StockOptionLevel) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.008164026684984015
Hence they are negatively correlated

__Correlation coefficient between Attrition and TotalWorkingYears__

In [70]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.TotalWorkingYears) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.16966991684723276
Hence they are negatively correlated

__Correlation coefficient between Attrition and YearsAtCompany__

In [71]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.YearsAtCompany) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.13300261842521066
Hence they are negatively correlated

__Correlation coefficient between Attrition and YearsWithCurrManager__

In [72]:
from scipy.stats import pearsonr 
stats,p = pearsonr(df1.Attrition,df1.YearsWithCurrManager) 

print('the value of correlation co-efficient :',stats)
if stats < 0:
    print("Hence they are negatively correlated")
elif stats > 0:
    print('Hence they are positively correlated')
elif stats == 0:
    print('Hence they are not correlated')

the value of correlation co-efficient : -0.15469153690286755
Hence they are negatively correlated